INFO:uvicorn.error:Started server process [19296]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [19296]
INFO:uvicorn.error:Started server process [10840]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [10840]
INFO:uvicorn.error:Started server process [6716]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [6716]
INFO:uvicorn.error:Started server process [1132]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response
  none is not an allowed value (type=type_error.none.not_allowed)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1132]
INFO:uvicorn.error:Started server process [22152]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [22152]
INFO:uvicorn.error:Started server process [588]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 138, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Message
response -> message
  field required (type=value_error.missing)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [588]
INFO:uvicorn.error:Started server process [21532]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [21532]
INFO:uvicorn.error:Started server process [21192]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\api\documentation_endpoints.py", line 47, in list_all_documents
    return res.json()
AttributeError: 'dict' object has no attribute 'json'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [21192]
INFO:uvicorn.error:Started server process [21240]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [21240]
INFO:uvicorn.error:Started server process [23924]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [23924]
INFO:uvicorn.error:Started server process [16560]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [16560]
INFO:uvicorn.error:Started server process [3896]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\api\documentation_endpoints.py", line 64, in get_documents
    return res.key()
AttributeError: 'dict' object has no attribute 'key'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3896]
INFO:uvicorn.error:Started server process [8784]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [8784]
INFO:uvicorn.error:Started server process [1020]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1020]
INFO:uvicorn.error:Started server process [16216]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [16216]
INFO:uvicorn.error:Started server process [1488]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1488]
INFO:uvicorn.error:Started server process [17684]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [17684]
INFO:uvicorn.error:Started server process [3944]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3944]
INFO:uvicorn.error:Started server process [4692]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [4692]
INFO:uvicorn.error:Started server process [17992]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [17992]
INFO:uvicorn.error:Started server process [17048]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [17048]
INFO:uvicorn.error:Started server process [15024]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [15024]
INFO:uvicorn.error:Started server process [18336]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [18336]
INFO:uvicorn.error:Started server process [8760]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [8760]
INFO:uvicorn.error:Started server process [8216]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_thread.lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [8216]
INFO:uvicorn.error:Started server process [5636]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 249, in app
    content = await serialize_response(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 149, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "pydantic\json.py", line 45, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [5636]
INFO:uvicorn.error:Started server process [15076]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\parserEnv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\ameli\OneDrive\Desktop\parser\actual_parser\SS-Parser-API\code\api\documentation_endpoints.py", line 71, in get_documents
    return res['Body'].read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 147: invalid start byte
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [15076]
INFO:uvicorn.error:Started server process [14680]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [14680]
INFO:uvicorn.error:Started server process [17248]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [17248]
INFO:uvicorn.error:Started server process [2600]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2600]
INFO:uvicorn.error:Started server process [2864]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2864]
INFO:uvicorn.error:Started server process [14556]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5050 (Press CTRL+C to quit)
INFO:botocore.credentials:Found credentials in environment variables.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [14556]
